trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: "ubuntu-latest"

variables:
  dockerfilePath: "OrderService.Api/Dockerfile"
  imageName: "order-service"
  containerRegistry: "DockerRegistryDevEnv.azurecr.io"
  azureSubscription: "ACR-FurnitureDropship" # Service connection name
  imageTag: "$(Build.BuildId)"

stages:
  - stage: Build
    displayName: "Build and Push Docker Image"
    jobs:
      - job: Docker
        displayName: "Docker Build and Push"
        steps:
          # Docker build and push to ACR
          - task: Docker@2
            displayName: "Build Docker image"
            inputs:
              command: "build"
              repository: "$(imageName)"
              dockerfile: "$(dockerfilePath)"
              buildContext: "$(Build.SourcesDirectory)"
              containerRegistry: "$(azureSubscription)"
              tags: |
                $(imageTag)
                latest

          - task: Docker@2
            displayName: "Push to ACR"
            inputs:
              command: "push"
              repository: "$(imageName)"
              containerRegistry: "$(azureSubscription)"
              tags: |
                $(imageTag)
                latest

          # Publish Kubernetes manifests
          - task: PublishBuildArtifacts@1
            displayName: "Publish K8s manifests"
            inputs:
              PathtoPublish: "$(Build.SourcesDirectory)/kubernetes"
              ArtifactName: "kubernetes-manifests"
              publishLocation: "Container"
