namespace OrderService.Data.Entities;

/// <summary>
/// Represents an order status lookup value
/// Maps to OrderStatuses table
/// </summary>
public class OrderStatus
{
    /// <summary>
    /// Primary key - auto-generated by database
    /// </summary>
    public int OrderStatusId { get; set; }

    /// <summary>
    /// Unique code for the status (e.g., "PENDING", "SHIPPED")
    /// </summary>
    public string StatusCode { get; set; } = string.Empty;

    /// <summary>
    /// Display name for the status
    /// </summary>
    public string StatusName { get; set; } = string.Empty;

    /// <summary>
    /// Optional description
    /// </summary>
    public string? StatusDescription { get; set; }

    /// <summary>
    /// Display order for UI
    /// </summary>
    public int DisplayOrder { get; set; }

    /// <summary>
    /// Whether this status is currently active
    /// </summary>
    public bool IsActive { get; set; } = true;

    /// <summary>
    /// When this status was created
    /// </summary>
    public DateTime CreatedDate { get; set; } = DateTime.UtcNow;

    // ===========================
    // Navigation Properties
    // ===========================

    /// <summary>
    /// Orders that have this status
    /// This is like a List<Order> in memory
    /// </summary>
    public ICollection<Order> Orders { get; set; } = new List<Order>();
}